//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.caijunxiong.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int id { get; set; }
        public int parent_id { get; set; }
        public string name { get; set; }
        public int type { get; set; }
        public string url { get; set; }
        public string target { get; set; }
        public int icon_type { get; set; }
        public string icon { get; set; }
        public bool active { get; set; }
        public int order { get; set; }
        public int depth { get; set; }
        public string parent_ids { get; set; }
        public string child_ids { get; set; }
        public string code { get; set; }
        public string description { get; set; }
    }
}
